default: &default
  encoding: UTF-8
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: story_chain
  password: story_chain
  port: 5432

development: &development
  adapter: postgresql
  encoding: unicode
  database: story_chain
  pool: 5
  username: liuyang
  password: root
  host: 127.0.0.1

test:
  <<: *development
  database: story_chain_test


production:
  <<: *development
